### ISSUE TITLE
Sample application for python(pip/poetry) not working with builder-jammy-base

### ISSUE THREAD

**Issue by yarora-clgx** [paketo-buildpacks/builder-jammy-base#408]
Hi Team,

I'm trying to build sample application of python(pip/poetry) available at [https://github.com/paketo-buildpacks/samples/tree/main/python](url) using builder-jammy-base but it is giving error while installing poetry.

## Command used:
 pack build sample-app --builder paketobuildpacks/builder-jammy-base

## Logs:

`7 of 10 buildpacks participating
paketo-buildpacks/ca-certificates 3.6.3
paketo-buildpacks/cpython         1.9.0
paketo-buildpacks/pip             0.18.0
paketo-buildpacks/poetry          0.6.5
paketo-buildpacks/poetry-install  0.3.17
paketo-buildpacks/python-start    0.14.14
paketo-buildpacks/procfile        5.6.4
===> RESTORING
===> BUILDING

Paketo Buildpack for CA Certificates 3.6.3
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Contributing to layer
    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
Paketo Buildpack for CPython 1.9.0
  Resolving CPython version
    Candidate version sources (in priority order):
      pyproject.toml -> "^3.10"
                     -> ""
      <unknown>      -> ""

    Selected CPython version (using pyproject.toml): 3.11.5

  Executing build process
    Installing CPython 3.11.5
      Completed in 12.875s

  Generating SBOM for /layers/paketo-buildpacks_cpython/cpython
      Completed in 0s

  Configuring build environment
    PYTHONPATH          -> "/layers/paketo-buildpacks_cpython/cpython"
    PYTHONPYCACHEPREFIX -> "/tmp"

  Configuring launch environment
    PYTHONPATH -> "/layers/paketo-buildpacks_cpython/cpython"

Paketo Buildpack for Pip 0.18.0
  Resolving Pip version
    Candidate version sources (in priority order):
       -> ""

    Selected Pip version (using ): 23.2.1

  Executing build process
    Installing Pip 23.2.1
      Completed in 22.339s

  Generating SBOM for /layers/paketo-buildpacks_pip/pip
      Completed in 0s

  Configuring build environment
    PIP_FIND_LINKS -> "$PIP_FIND_LINKS /layers/paketo-buildpacks_pip/pip-source"

  Configuring build environment
    PYTHONPATH -> "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages:$PYTHONPATH"

  Configuring launch environment
    PYTHONPATH -> "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages:$PYTHONPATH"

Paketo Buildpack for Poetry 0.6.5
  Resolving Poetry version
    Candidate version sources (in priority order):
      <unknown> -> ""

    Selected Poetry version (using <unknown>): 1.4.2

  Executing build process
    Installing Poetry 1.4.2
failed to configure poetry:
Looking in links: /layers/paketo-buildpacks_pip/pip-source
Collecting poetry==1.4.2
  Downloading poetry-1.4.2-py3-none-any.whl (222 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 609, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
           ^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 52, in _rich_progress_bar
    with progress:
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/rich/progress.py", line 1169, in __enter__
    self.start()
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/rich/progress.py", line 1160, in start
    self.live.start(refresh=True)
  File "/layers/paketo-buildpacks_pip/pip/lib/python3.11/site-packages/pip/_vendor/rich/live.py", line 132, in start
    self._refresh_thread.start()
  File "/layers/paketo-buildpacks_cpython/cpython/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip

error: exit status 2
ERROR: failed to build: exit status 1`

## Observation
While using "paketobuildpacks/builder:base" builder the sample application is build successfully and docker image is being created successfully.

Please suggest if any additional parameters are required during build or is there issue with builder-jammy-base.

**Comment by yarora-clgx** [comment]
There was some repository issues which was causing the issues.

Removed the repos and it worked fine.
